name: Build and Push to ECR using OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::905418099027:role/ecr-role
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: |
        docker build -t actions-to-ecr .

    - name: Tag Docker Image
      run: |
        docker tag actions-to-ecr:latest ${{ steps.ecr-login.outputs.registry }}/actions-to-ecr:latest

    - name: Push Docker Image to ECR
      run: |
        docker push ${{ steps.ecr-login.outputs.registry }}/actions-to-ecr:latest
